apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: snmpd-daemonset
spec:
  selector:
    matchLabels:
      app: snmpd
  template:
    metadata:
      labels:
        app: snmpd
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: snmpd
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort }}
          hostPort: {{ .hostPort }}
          protocol: {{ .protocol }}
        {{- end }}
        volumeMounts:
        - name: snmpd-config
          mountPath: /etc/snmp/snmpd.conf
          subPath: snmpd.conf
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
      volumes:
      - name: snmpd-config
        configMap:
          name: snmpd-config
