apiVersion: v1
kind: Service
metadata:
  name: snmpd-service
spec:
  selector:
    app: snmpd
  ports:
  - name: snmp-tcp
    port: 161
    protocol: TCP
    nodePort: 3161
  - name: snmp-trap-tcp
    port: 162
    protocol: TCP
    nodePort: 3162
  - name: snmp-udp
    port: 161
    protocol: UDP
    nodePort: 3161
  - name: snmp-trap-udp
    port: 162
    protocol: UDP
    nodePort: 3162
  type: NodePort
